trigger:
  batch: true
  branches:
    include:
    - master
    - ?.?*  # matches to backport branches, e.g. 3.6
  tags:
    exclude:
    - '*'
pr:
  autoCancel: true
  branches:
    include:
    - master
    - ?.?*  # matches to backport branches, e.g. 3.6

resources:
  containers:
  - container: manylinux
    image: quay.io/pypa/manylinux1_x86_64
  repositories:
  - repository: templates
    type: github
    name: aio-libs/azure-pipelines
    endpoint: aio-libs

variables:
- group: codecov

stages:
- template: stage-lint.yml
- template: stage-test.yml
- template: templates/stage-test-aarch64.yml@templates
  parameters:
    steps: $PYTHON setup.py install && $PYTHON -m pip install -r requirements/pytest.txt && \
